import fs from 'node:fs'
const root = new URL('../', import.meta.url)
const read = (p) => fs.readFileSync(new URL(p, root), 'utf8').replace(/\r\n/g, '\n')
const output = `// dsh-note-changes · Client half (v1.11.0)\n// Generated by tools/build-client.mjs; edit client/ sources.\nwindow.__ModuleLoader__.load({id:'dsh-note-changes',factory:(require)=>{\nvar exports={},React=require('react'),h=React.createElement;\nvar CSS=${JSON.stringify(read('client/styles.css'))};\n${read('client/markdown.part.js')}\n${read('client/plus.part.js')}\n${read('client/workspace.part.js')}\nreturn exports;\n}});\n`
if (process.argv.includes('--check')) {
  if (read('client.js') !== output) throw new Error('client.js needs rebuilding')
} else fs.writeFileSync(new URL('client.js', root), output)
